### ISSUE TITLE
Server Infrastructure

### ISSUE THREAD

**Issue by sebrock** [BananoCoin/BananoNault#15]
Provide a VPS for

- [ ] Development Server instance #16 
- [ ] Test Server Instance #17 
- [ ] Production Server Instance #18
