### ISSUE TITLE
BUNDLE: Fonts

### ISSUE THREAD

**Issue by sebrock** [BananoCoin/BananoNault#5]
Bundle of activities required to apply Banano fonts.
Add activities and link related Issues as needed.

- [x]  Provide Fonts: Issue #1 

- [ ] Identify where code needs to be adapted to apply Banano fonts: Issue #3 

- [ ] Amend code to apply Banano fonts: Issue #4 

- [ ] Test fonts: Issue #6
